baseURL = 'https://fhaurie.fr/'
languageCode = 'fr-FR'
title = 'François Haurie'
theme = 'terminal'
[params]
contentTypeName = "posts"
showMenuItems = 10
fullWidthTheme = false
centerTheme = true

[[languages.fr.menu.main]]
identifier = "cv"
name = "CV"
url = "/docs/00%20CV%20HAURIE%20FRANCOIS%20MAJ8126.pdf"
weight = 10

[[languages.fr.menu.main]]
identifier = "diplome-niv4"
name = "Diplôme NIV 4"
url = "/docs/01%20Diplome%20NIV%20Agent%20de%20protection%20des%20personnes%20NIV%204.pdf"
weight = 20

[[languages.fr.menu.main]]
identifier = "conducteur-autorite"
name = "Conducteur d'autorité ASP"
url = "/docs/02%20Certificat%20de%20conducteur%20d%27autorite%20ASP.pdf"
weight = 30

[[languages.fr.menu.main]]
identifier = "epo"
name = "Executive Protection Officer"
url = "/docs/03%20Executive%20protection%20officier%20EPO.pdf"
weight = 40

[[languages.fr.menu.main]]
identifier = "psd"
name = "Protective Security Detail"
url = "/docs/04%20Protective%20security%20detail%20PSD.pdf"
weight = 50

[[languages.fr.menu.main]]
identifier = "tecc"
name = "TECC Tactical Emergency"
url = "/docs/05%20Certificat%20T%20E%20C%20C%20Tactical%20Emergency%20Casualty%20Care.pdf"
weight = 60

[[languages.fr.menu.main]]
identifier = "pistol"
name = "Pistol Basic Training"
url = "/docs/06%20Certificat%20Pistol%20Basic%20Training.pdf"
weight = 70

[[languages.fr.menu.main]]
identifier = "fekm-cn1"
name = "Krav Maga CN1"
url = "/docs/francois-fekm-cn1.jpg"
weight = 80

[[languages.fr.menu.main]]
identifier = "fekm-dif"
name = "Krav Maga DIF"
url = "/docs/francois-fekm-dif.jpg"
weight = 90

[languages]
[languages.fr]
languageName = "Français"
title = "François Haurie"
[languages.fr.params.logo]
logoText = "François Haurie"
logoHomeLink = "/"


[caches]
[caches.images]
dir = ':cacheDir/images'

[module]
# this is needed when you fetch the theme as a submodule to your repo.
# replacements = "github.com/panr/hugo-theme-terminal/4 -> themes/terminal"
[[module.imports]]
path = 'github.com/panr/hugo-theme-terminal/v4'
