baseURL = 'https://fhaurie.fr/'
languageCode = 'fr-FR'
title = 'François Haurie'
theme = 'terminal'
[params]
contentTypeName = "posts"
showMenuItems = 10
fullWidthTheme = false
centerTheme = true

[[languages.fr.menu.main]]
identifier = "cv"
name = "CV"
url = "/docs/00-cv-haurie-francois-maj8126.pdf"
weight = 10

[[languages.fr.menu.main]]
identifier = "diplome-niv4"
name = "Diplôme NIV 4"
url = "/docs/01-diplome-niv-agent-de-protection-des-personnes-niv-4.pdf"
weight = 20

[[languages.fr.menu.main]]
identifier = "conducteur-autorite"
name = "Conducteur d'autorité ASP"
url = "/docs/02-certificat-de-conducteur-dautorite-asp.pdf"
weight = 30

[[languages.fr.menu.main]]
identifier = "epo"
name = "Executive Protection Officer"
url = "/docs/03-executive-protection-officier-epo.pdf"
weight = 40

[[languages.fr.menu.main]]
identifier = "psd"
name = "Protective Security Detail"
url = "/docs/04-protective-security-detail-psd.pdf"
weight = 50

[[languages.fr.menu.main]]
identifier = "tecc"
name = "TECC Tactical Emergency"
url = "/docs/05-certificat-t-e-c-c-tactical-emergency-casualty-care.pdf"
weight = 60

[[languages.fr.menu.main]]
identifier = "pistol"
name = "Pistol Basic Training"
url = "/docs/06-certificat-pistol-basic-training.pdf"
weight = 70

[[languages.fr.menu.main]]
identifier = "fekm-cn1"
name = "Krav Maga CN1"
url = "/docs/francois-fekm-cn1.jpg"
weight = 80

[[languages.fr.menu.main]]
identifier = "fekm-dif"
name = "Krav Maga DIF"
url = "/docs/francois-fekm-dif.jpg"
weight = 90

[languages]
[languages.fr]
languageName = "Français"
title = "François Haurie"
[languages.fr.params.logo]
logoText = "François Haurie"
logoHomeLink = "/"


[caches]
[caches.images]
dir = ':cacheDir/images'

[module]
# this is needed when you fetch the theme as a submodule to your repo.
# replacements = "github.com/panr/hugo-theme-terminal/4 -> themes/terminal"
[[module.imports]]
path = 'github.com/panr/hugo-theme-terminal/v4'
