baseURL = 'https://fhaurie.fr/'
languageCode = 'fr-FR'
title = 'François Haurie'
theme = 'terminal'
[params]
contentTypeName = "posts"
showMenuItems = 2
fullWidthTheme = false
centerTheme = true

[languages]
[languages.fr]
languageName = "Français"
title = "François Haurie"
[languages.fr.params.logo]
logoText = "François Haurie"
logoHomeLink = "/"


[caches]
[caches.images]
dir = ':cacheDir/images'

[module]
# this is needed when you fetch the theme as a submodule to your repo.
# replacements = "github.com/panr/hugo-theme-terminal/4 -> themes/terminal"
[[module.imports]]
path = 'github.com/panr/hugo-theme-terminal/v4'
